### ISSUE TITLE
1 clic deploy failing with error

### ISSUE THREAD

**Issue by Tristan-Soriano** [looker/lookerbot#183]
Hi,
The 1 clic deploy fails due to missing dependency:

2020-05-11T19:43:48.676184+00:00 heroku[web.1]: State changed from starting to crashed
2020-05-11T19:43:48.680370+00:00 heroku[web.1]: State changed from crashed to starting
2020-05-11T19:43:57.595122+00:00 app[web.1]: yarn run v1.19.1
2020-05-11T19:43:57.668718+00:00 app[web.1]: $ ./node_modules/.bin/ts-node ./src/index.ts
2020-05-11T19:44:05.751687+00:00 app[web.1]: Error: Cannot find module 'skills-validator'
2020-05-11T19:44:05.751713+00:00 app[web.1]: Require stack:
2020-05-11T19:44:05.751714+00:00 app[web.1]: - /app/node_modules/botbuilder/lib/bots/ChatConnector.js
2020-05-11T19:44:05.751714+00:00 app[web.1]: - /app/node_modules/botbuilder/lib/botbuilder.js
2020-05-11T19:44:05.751715+00:00 app[web.1]: - /app/node_modules/botkit/lib/BotFramework.js
2020-05-11T19:44:05.751715+00:00 app[web.1]: - /app/node_modules/botkit/lib/Botkit.js
2020-05-11T19:44:05.751715+00:00 app[web.1]: - /app/src/services/slack_service.ts
2020-05-11T19:44:05.751716+00:00 app[web.1]: - /app/src/index.ts
2020-05-11T19:44:05.751716+00:00 app[web.1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
2020-05-11T19:44:05.751717+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:890:27)
2020-05-11T19:44:05.751717+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:1080:19)
2020-05-11T19:44:05.751718+00:00 app[web.1]: at require (internal/modules/cjs/helpers.js:72:18)
2020-05-11T19:44:05.751718+00:00 app[web.1]: at Object.<anonymous> (/app/node_modules/botbuilder/lib/bots/ChatConnector.js:15:26)
2020-05-11T19:44:05.751718+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:1176:30)
2020-05-11T19:44:05.751719+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
2020-05-11T19:44:05.751719+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:1040:32)
2020-05-11T19:44:05.751719+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:929:14)
2020-05-11T19:44:05.751720+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:1080:19)
2020-05-11T19:44:05.794091+00:00 app[web.1]: error Command failed with exit code 1.
2020-05-11T19:44:05.794371+00:00 app[web.1]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2020-05-11T19:44:05.888519+00:00 heroku[web.1]: State changed from starting to crashed

Any suggestion ?

**Comment by ritzforce** [comment]
Hi @Tristan-Soriano 
I am facing the same issue. 
How did you resolve it ?
